server:
  port: 80
  address: 0.0.0.0

spring:
  data:
    mongodb:
      uri: mongodb+srv://dioniMongo:f9crxVmimikMQsj1@cluster0.nnzbs.mongodb.net/adn_checker?retryWrites=true&w=majority
      database: adn_checker
      auto-index-creation: true