server:
  port: 80
  address: 0.0.0.0


management:
  endpoints:
    web:
      base-path:

info:
  status: UP

spring:
  datasource:
    url: jdbc:mysql://${MYSQL_HOST:localhost}:${MYSQL_PORT:3306}/${MYSQL_DB_NAME:db_mutant}?serverTimezone=America/Bogota&allowPublicKeyRetrieval=true&useSSL=false
    username: ${MYSQL_USERNAME:root}
    password: ${MYSQL_PASSWORD:1234}
  jpa:
    show-sql: true
